export const URLS = {
  HOME: "./",
  GOOD_ANSWERS: "./dobre-odpowiedzi",
  BAD_ANSWERS: "./zle-odpowiedzi",
  QUESTION_1: "./id99",
  USER_ACCONT: "./twoje-konto",
  QUESTION_TABLE: "./pytania-z-testow-na-prawo-jazdy",
  DRIVING_LICENSE_CATEGIRIES: "./kategorie-prawa-jazdy",
  PRICING: "./cennik",
  BLOG: "./blog",
  COURSES: "./szkolenia",
  CONTACT: "./kontakt",
  PRIVACY_POLICY: "./polityka-prywatnosci",
  TERMS_AND_CONDITIONS: "./regulamin",
} as const;
