export const DEFAUTL_INITIAL_CURRENT_CATEGORY_VALUE = "b";

export const SESSION_STORAGE_KEY = {
  CURRENT_CATEGORY: "CURRENT_CATEGORY",
  API_DATA: "API_DATA",
  CATEGORIES: "CATEGORIES",
} as const;
